module Seeds
  module UsAddresses
    LIST = [
      "1415 Pinecrest Rd, Miami, FL, USA",
      "1250 Oakwood St, Austin, TX, USA",
      "2547 Maple Ave, Los Angeles, CA, USA",
      "890 Pine Hill Rd, New York, NY, USA",
      "3325 Cedar Blvd, Houston, TX, USA",
      "1856 Elm St, Chicago, IL, USA",
      "4064 Birch Ln, Seattle, WA, USA",
      "2098 Spruce Dr, Denver, CO, USA",
      "7543 Walnut Way, San Francisco, CA, USA",
      "1209 Redwood Rd, Dallas, TX, USA",
      "876 Cedar Ave, Portland, OR, USA",
      "4329 Cherry Blossom Rd, San Diego, CA, USA",
      "2031 Willow Creek Dr, Phoenix, AZ, USA",
      "7546 Birchwood Blvd, Miami, FL, USA",
      "1801 Oakmont Dr, Minneapolis, MN, USA",
      "957 Pinecone St, Boston, MA, USA",
      "6204 Dogwood Rd, Cleveland, OH, USA",
      "3027 Maple Grove Ln, Orlando, FL, USA",
      "1012 Hawthorne Ave, Atlanta, GA, USA",
      "8743 Valley Forge Dr, Philadelphia, PA, USA",
      "2789 Cypress Hill Dr, Salt Lake City, UT, USA",
      "5634 Hilltop Ln, Charlotte, NC, USA",
      "4331 Red Oak Rd, Richmond, VA, USA",
      "2201 Birchwood Ln, Nashville, TN, USA",
      "3036 Aspen Blvd, Denver, CO, USA",
      "5642 Magnolia St, Detroit, MI, USA",
      "3108 Fernwood Dr, Washington, DC, USA",
      "9012 Beechwood Dr, Tampa, FL, USA",
      "7054 Evergreen Way, Kansas City, MO, USA",
      "1829 Cloverhill Dr, Indianapolis, IN, USA",
      "3021 Forest Dr, St. Louis, MO, USA",
      "5076 Spruce Ln, Austin, TX, USA",
      "3245 Willow Rd, Los Angeles, CA, USA",
      "9512 Oak Ridge Dr, Dallas, TX, USA",
      "6013 Maplewood Ave, Miami, FL, USA",
      "1245 Birch Rd, Phoenix, AZ, USA",
      "3571 Pine Dr, Chicago, IL, USA",
      "4630 Oak St, Portland, OR, USA",
      "2598 Maple Leaf Dr, Seattle, WA, USA",
      "1034 Elmwood St, San Francisco, CA, USA",
      "8317 Pinebrook Ave, Denver, CO, USA",
      "6208 Cedarwood Ln, Houston, TX, USA",
      "1482 Dogwood Dr, Atlanta, GA, USA",
      "3084 Aspen Ridge Rd, New York, NY, USA",
      "2413 Magnolia Way, Salt Lake City, UT, USA",
      "5390 Valley View Dr, San Diego, CA, USA",
      "1005 Birch Grove Rd, Boston, MA, USA",
      "3981 Redwood Dr, Portland, OR, USA",
      "1296 Oak Lane, Richmond, VA, USA",
      "5729 Hawthorne Ave, Tampa, FL, USA",
      "4916 Pinehill Rd, Charlotte, NC, USA",
      "3254 Cedar Ridge Rd, Cleveland, OH, USA",
      "2573 Willowbrook Ave, Indianapolis, IN, USA",
      "4157 Maplewood Dr, Kansas City, MO, USA",
      "6674 Spruce Hill Rd, Phoenix, AZ, USA",
      "9824 Birchview Ln, Los Angeles, CA, USA",
      "1325 Cedarwood Dr, Seattle, WA, USA",
      "5268 Willow Dr, Dallas, TX, USA",
      "3167 Magnolia Ridge Rd, Chicago, IL, USA",
      "1465 Birchwood Ln, San Francisco, CA, USA",
      "7102 Pinecrest St, Miami, FL, USA",
      "2153 Cedar Dr, Washington, DC, USA",
      "8831 Oakfield Rd, St. Louis, MO, USA",
      "5174 Redwood Rd, Salt Lake City, UT, USA",
      "3602 Maplewood Ln, Richmond, VA, USA",
      "4001 Spruce St, Atlanta, GA, USA",
      "1723 Magnolia Dr, Kansas City, MO, USA",
      "2647 Pinehill Rd, San Diego, CA, USA",
      "5175 Oakwood Dr, Cleveland, OH, USA",
      "6783 Willow Lane, Portland, OR, USA",
      "9504 Cedar Lane, New York, NY, USA",
      "2115 Maple Ave, Los Angeles, CA, USA",
      "3274 Birch Ln, Phoenix, AZ, USA",
      "4896 Oakbrook Rd, Denver, CO, USA",
      "5610 Pine Grove Dr, Charlotte, NC, USA",
      "1032 Cedarwood Ave, Houston, TX, USA",
      "6345 Birchview Ave, Tampa, FL, USA",
      "4078 Redwood Rd, St. Louis, MO, USA",
      "7421 Willow Dr, Indianapolis, IN, USA",
      "3298 Oak Ridge Ln, San Francisco, CA, USA",
      "5840 Birchwood Ave, Washington, DC, USA",
      "4732 Pinebrook Rd, Dallas, TX, USA",
      "6983 Maple Rd, Atlanta, GA, USA",
      "1287 Cedar Ln, Chicago, IL, USA",
      "1842 Oak Dr, Los Angeles, CA, USA",
      "2637 Redwood Dr, Phoenix, AZ, USA",
      "5934 Willow Rd, Portland, OR, USA",
      "4002 Pinecrest Dr, Salt Lake City, UT, USA",
      "8257 Maple Grove Rd, San Diego, CA, USA",
      "1375 Birchwood Ave, Houston, TX, USA",
      "6731 Oakwood Rd, Miami, FL, USA",
      "7104 Pine St, Philadelphia, PA, USA",
      "2946 Willow Lane, Kansas City, MO, USA",
      "5392 Cedar Ave, Denver, CO, USA",
      "1067 Redwood St, Tampa, FL, USA",
      "2640 Magnolia Ave, Charlotte, NC, USA",
      "3259 Pineview Dr, Cleveland, OH, USA",
      "1486 Birch Rd, Austin, TX, USA",
      "5771 Maple Lane, Phoenix, AZ, USA",
      "9482 Pine Grove St, Seattle, WA, USA",
      "1142 Cedar St, St. Louis, MO, USA",
      "3651 Oak Blvd, Richmond, VA, USA",
      "2701 Birch Rd, Portland, OR, USA"
    ]
  end
end
